### ISSUE TITLE
Add  coverage testing

### ISSUE THREAD

**Issue by JJ** [JJ/raku-test-action#2]
It would be extremely convenient, and pretty lightweight, to use @atroxaper's [RaCoCo](https://github.com/atroxaper/raku-RaCoCo) to show coverage.

**Comment by atroxaper** [comment]
It would be so simple with https://raku.land/zef:atroxaper/App::Racoco::Report::ReporterCoveralls and https://coveralls.io

**Comment by atroxaper** [comment]
Or I misunderstand your idea😅

**Comment by JJ** [comment]
No, totally correct.
